name: GitHub Classroom Workflow

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  TZ: Asia/Shanghai # 设置时区
  API_URL: "aHR0cHM6Ly9hcGkub3BlbmNhbXAuY24vd2ViL2FwaS9jb3Vyc2VSYW5rL2NyZWF0ZUJ5VGhpcmRUb2tlbg=="
  TOKEN: "bXJua242eXp0NXFUYm9DR1ZEb25QOWIzU2lNQ0hw"
  
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    outputs:
      details: ${{ steps.autograding.outputs.details }}
      points: ${{ steps.autograding.outputs.points }}
    steps:
    - name: Decode API URL
      id: decode_api_url
      run: |
        echo "url=$(echo "$API_URL" | base64 --decode)" >> $GITHUB_ENV
    - name: Decode Token
      id: decode_token
      run: |
        echo "token=$(echo "$TOKEN" | base64 --decode)" >> $GITHUB_ENV
    - uses: actions/checkout@v3
    - name: Run tests
      run: cargo test --test cicv --verbose
    - uses: yfblock/os-autograding@master
      id: autograding
      with:
        outputFile: .github/result/check_result.json
    - name: Generate summary JSON
      run: |
        outfile=".github/result/check_result.json"
        summary_file=".github/result/summary.json"

        # 提取需要的值
        total_exercations=$(jq '.statistics.total_exercations' $outfile)
        total_succeeds=$(jq '.statistics.total_succeeds' $outfile)
        github_user="${{ github.actor }}"

        # 生成新的 JSON 内容
        new_json=$(jq -n \
          --arg channel "github" \
          --argjson courseId 1528 \
          --arg ext "aaa" \
          --arg name "$github_user" \
          --argjson score "$total_succeeds" \
          --argjson totalScore "$total_exercations" \
          '{channel: $channel, courseId: $courseId, ext: $ext, name: $name, score: $score, totalScore: $totalScore}')

        # 保存新的 JSON 文件
        echo "$new_json" > $summary_file

        # 打印新的 JSON 文件到终端
        cat $summary_file
    - name: Post summary JSON to remote API
      run: |
        summary_file=".github/result/summary.json"

        # 发送 POST 请求
        curl -X POST "$url" \
          -H "accept: application/json;charset=utf-8" \
          -H "Content-Type: application/json" \
          -H "token: $token" \
          -d "$(cat $summary_file)" \
          -v
